
apache:
    #image: php:apache
    container_name: apache
    build: ./dev
    volumes:
    - "/root/websocket3/src/:/var/www/html/"
    - "/root/websocket3/testangular6:/usr/src/"
    - "/root/websocket3/dev/sites-available/:/etc/apache2/sites-available/"
    - "/root/websocket3/nodewebsocket/:/usr/websocket/"
    ports:
    - "8080:8080"
    - "443:443"
    privileged: true